src/main/java/kb04/team02/web/mvc/domain/wallet/common/ForeignCurrencyBalance.java
src/main/java/kb04/team02/web/mvc/domain/wallet/common/Transfer.java
src/main/java/kb04/team02/web/mvc/domain/wallet/common/WalletExchange.java
src/main/java/kb04/team02/web/mvc/dto/PersonalWalletDto.java
src/main/java/kb04/team02/web/mvc/dto/WalletHistoryDto.java
src/main/java/kb04/team02/web/mvc/service/personalwallet/PersonalWalletService.java
src/main/java/kb04/team02/web/mvc/service/personalwallet/PersonalWalletServiceImpl.java

Feat: 개인지갑 서비스 및 DTO #4

---

src/main/java/kb04/team02/web/mvc/controller/exchange/ExchangeController.java
src/main/java/kb04/team02/web/mvc/repository/bank/BankRepository.java
src/main/java/kb04/team02/web/mvc/repository/bank/ExchangeRateReposotory.java
src/main/java/kb04/team02/web/mvc/repository/bank/OfflineReceiptRepository.java
src/main/java/kb04/team02/web/mvc/service/exchange/ExchangeService.java
src/main/java/kb04/team02/web/mvc/service/exchange/ExchangeServiceImpl.java

Feat: 환전 서비스 인터페이스 #1

---

src/main/java/kb04/team02/web/mvc/controller/exchange/ExchangeController.java
src/main/java/kb04/team02/web/mvc/dto/ExchangeDto.java
src/main/java/kb04/team02/web/mvc/service/exchange/ExchangeService.java

Feat: 온라인 환전 인터페이스 작성 #14

---

src/main/java/kb04/team02/web/mvc/controller/groupwallet/GroupWalletTabController.java
src/main/java/kb04/team02/web/mvc/dto/CardIssuanceDto.java
src/main/java/kb04/team02/web/mvc/dto/GroupMemberDto.java
src/main/java/kb04/team02/web/mvc/dto/RuleDto.java
src/main/java/kb04/team02/web/mvc/dto/SavingDto.java
src/main/java/kb04/team02/web/mvc/service/groupwallet/GroupWalletTabService.java

1. 모임지갑 탭서비스 인터페이스 수정
controller > service로 보낼 때 모임지갑 id와 모임원 member의 타입을 String > Long으로 변환
DTO 수정
2. 모임지갑 탭서비스 관련 DTO 상세 작성
GroupMemberDto
RuleDto
SavingDto 
CardIssuanceDto
WalletHistoryDto(이미 만들어짐)

모임지갑 탭서비스 인터페이스 수정 및 관련 DTO 작성 #15

---

src/main/java/kb04/team02/web/mvc/controller/member/MemberController.java
src/main/java/kb04/team02/web/mvc/dto/LoginMemberDto.java
src/main/java/kb04/team02/web/mvc/dto/MemberLoginDto.java
src/main/java/kb04/team02/web/mvc/dto/MemberRegisterDto.java
src/main/java/kb04/team02/web/mvc/exception/LoginException.java
src/main/java/kb04/team02/web/mvc/exception/RegisterException.java
src/main/java/kb04/team02/web/mvc/repository/member/MemberRepository.java
src/main/java/kb04/team02/web/mvc/repository/wallet/group/GroupWalletRespository.java
src/main/java/kb04/team02/web/mvc/repository/wallet/group/ParticipationRepository.java
src/main/java/kb04/team02/web/mvc/service/member/MemberService.java
src/main/java/kb04/team02/web/mvc/service/member/MemberServiceImpl.java

Feat: 회원가입, 로그인 서비스 구현 #16

---

src/main/java/kb04/team02/web/mvc/domain/wallet/group/GroupWallet.java
src/main/java/kb04/team02/web/mvc/repository/wallet/group/GroupWalletRespository.java
src/main/java/kb04/team02/web/mvc/service/groupwallet/GroupWalletService.java
src/main/java/kb04/team02/web/mvc/service/groupwallet/GroupWalletServiceImpl.java

GroupWallet 도메인에 Setter 추가 #13

Feat: 모임지갑 Rep, Ser, 서비스Impl

---

src/main/java/kb04/team02/web/mvc/common/module/CardNumberIssuance.java
src/main/java/kb04/team02/web/mvc/domain/card/CardIssuance.java
src/main/java/kb04/team02/web/mvc/domain/member/Member.java
src/main/java/kb04/team02/web/mvc/domain/wallet/personal/PersonalWallet.java
src/main/java/kb04/team02/web/mvc/dto/LoginMemberDto.java
src/main/java/kb04/team02/web/mvc/repository/card/CardIssuanceRepository.java
src/main/java/kb04/team02/web/mvc/service/common/module/CardNumberIssuance.java
src/main/java/kb04/team02/web/mvc/service/member/MemberServiceImpl.java
src/main/java/kb04/team02/web/mvc/service/mypage/MyPageService.java
src/main/java/kb04/team02/web/mvc/service/mypage/MyPageServiceImpl.java

Feat: 마이페이지 서비스 구현 #30

---

src/main/java/kb04/team02/web/mvc/controller/groupwallet/GroupWalletController.java
src/main/java/kb04/team02/web/mvc/domain/wallet/group/GroupWallet.java
src/main/java/kb04/team02/web/mvc/domain/wallet/group/GroupWalletForeignCurrencyBalance.java
src/main/java/kb04/team02/web/mvc/repository/wallet/group/GroupWalletExchangeRepository.java
src/main/java/kb04/team02/web/mvc/repository/wallet/group/GroupWalletForeignCurrencyBalanceRepository.java
src/main/java/kb04/team02/web/mvc/repository/wallet/group/GroupWalletPaymentRepository.java
src/main/java/kb04/team02/web/mvc/repository/wallet/group/GroupWalletRespository.java
src/main/java/kb04/team02/web/mvc/repository/wallet/group/GroupWalletTransferRepository.java
src/main/java/kb04/team02/web/mvc/service/groupwallet/GroupWalletService.java
src/main/java/kb04/team02/web/mvc/service/groupwallet/GroupWalletServiceImpl.java
src/test/java/kb04/team02/web/mvc/repository/wallet/group/GroupWalletRepositoryTest.java

모임지갑 서비스 테스트 #27

---

pom.xml
src/main/java/kb04/team02/web/mvc/controller/groupwallet/GroupWalletTabController.java

모임지갑 탭 컨트롤러 Feat/#43

---

src/main/java/kb04/team02/web/mvc/controller/groupwallet/GroupWalletTabController.java

필요한 parameter 추가 #43

---

src/main/java/kb04/team02/web/mvc/controller/groupwallet/GroupWalletController.java
src/main/java/kb04/team02/web/mvc/domain/wallet/common/SettleType.java
src/main/java/kb04/team02/web/mvc/domain/wallet/group/GroupWalletForeignCurrencyBalance.java
src/main/java/kb04/team02/web/mvc/dto/DepositDto.java
src/main/java/kb04/team02/web/mvc/dto/SettleDto.java
src/main/java/kb04/team02/web/mvc/dto/WithDrawDto.java
src/main/java/kb04/team02/web/mvc/exception/NotEnoughBalanceException.java
src/main/java/kb04/team02/web/mvc/exception/WalletDeleteException.java
src/main/java/kb04/team02/web/mvc/repository/wallet/group/GroupWalletExchangeRepository.java
src/main/java/kb04/team02/web/mvc/repository/wallet/group/GroupWalletForeignCurrencyBalanceRepository.java
src/main/java/kb04/team02/web/mvc/service/groupwallet/GroupWalletService.java
src/main/java/kb04/team02/web/mvc/service/groupwallet/GroupWalletServiceImpl.java
src/main/resources/application.properties
src/test/java/kb04/team02/web/mvc/KbFinalApplicationTests.java
src/test/java/kb04/team02/web/mvc/repository/wallet/group/GroupWalletForeignCurrencyBalanceRepositoryTest.java
src/test/java/kb04/team02/web/mvc/repository/wallet/group/GroupWalletRepositoryTest.java
src/test/java/kb04/team02/web/mvc/service/groupwallet/GroupWalletServiceImplTest.java
src/test/java/kb04/team02/web/mvc/service/groupwallet/GroupWalletTabServiceImplTest.java

모임지갑 기능 추가

---

src/main/webapp/WEB-INF/views/index.jsp
src/main/webapp/WEB-INF/views/member/register.jsp

index.jsp, register.jsp form으로 controller에 데이터 보내기 #53

---

src/main/java/kb04/team02/web/mvc/exchange/service/ExchangeServiceImpl.java
src/main/java/kb04/team02/web/mvc/group/service/GroupWalletServiceImpl.java
src/main/java/kb04/team02/web/mvc/group/service/GroupWalletTabServiceImpl.java
src/main/java/kb04/team02/web/mvc/mypage/service/MyPageServiceImpl.java
src/main/java/kb04/team02/web/mvc/personal/service/PersonalWalletServiceImpl.java
src/main/java/kb04/team02/web/mvc/saving/service/SavingServiceImpl.java

Fix: 서비스 코드 예외처리 수정 및 정리

---

pom.xml
src/main/java/kb04/team02/web/mvc/common/aop/LoggingAspect.java
src/main/resources/application.properties
src/main/resources/logback-spring.xml

- spring-aop 로 controller 메소드 실행 전후 로그 찍힙니다. 
- 조인포인트 실행 전 파라미터도 찍히니까 값 확인하려면 DTO 에 toString() 오버라이딩 하세요!
#82

Feat: 로그 출력 #82

---

src/main/java/kb04/team02/web/mvc/member/controller/MemberController.java

@SessionAttributes("member") 삭제 #86

---

src/main/java/kb04/team02/web/mvc/saving/controller/SavingController.java
src/main/java/kb04/team02/web/mvc/saving/dto/SavingInstallmentDto.java
src/main/webapp/WEB-INF/views/saving/savingForm.jsp

적금 가입 완료
- maturity_date가 자동으로 테이블에 들어가지 않아 서비스 단 로직 내일 짜야겠음

적금 가입 완료 #106

---

src/main/java/kb04/team02/web/mvc/member/controller/MemberController.java
src/main/java/kb04/team02/web/mvc/member/service/MemberService.java
src/main/java/kb04/team02/web/mvc/member/service/MemberServiceImpl.java
src/main/webapp/WEB-INF/views/common/virtualKeyboard.jsp
src/main/webapp/WEB-INF/views/groupwallet/depositForm.jsp
src/main/webapp/WEB-INF/views/groupwallet/groupWalletWithdrawForm.jsp
src/main/webapp/WEB-INF/views/personalwallet/depositForm.jsp
src/main/webapp/WEB-INF/views/personalwallet/withdrawForm.jsp

- 모임 지갑 채우기/꺼내기 컨트롤러 주석 처리 되어있는거 일단 두었습니다. 수정 필요.

Feat: 가상 키보드 #103

---

src/main/java/kb04/team02/web/mvc/saving/controller/SavingController.java
src/main/java/kb04/team02/web/mvc/saving/repository/InstallmentSavingRepository.java
src/main/java/kb04/team02/web/mvc/saving/service/SavingService.java
src/main/java/kb04/team02/web/mvc/saving/service/SavingServiceImpl.java
src/main/webapp/WEB-INF/views/mypage/main.jsp

적금 선택하고 해당 모임지갑으로 가입하고자 할 때 가입 불가능하게 막아놓음

해당 모임지갑으로 이미 적금 가입되어있으면 또 가입 못하게 수정 #117

---

src/main/java/kb04/team02/web/mvc/group/controller/GroupWalletController.java
src/main/java/kb04/team02/web/mvc/group/controller/GroupWalletTabController.java
src/main/java/kb04/team02/web/mvc/group/service/GroupWalletTabService.java
src/main/java/kb04/team02/web/mvc/group/service/GroupWalletTabServiceImpl.java
src/main/java/kb04/team02/web/mvc/saving/repository/InstallmentSavingRepository.java
src/test/java/kb04/team02/web/mvc/service/groupwallet/GroupWalletTabServiceImplTest.java

- 만기 시 이자 포함하여 모임통장에 돈 입금
- 만기 전 이자 포함하지 않고 모임통장에 돈 입금

적금 해지 로직 #149

---

src/main/java/kb04/team02/web/mvc/group/service/GroupWalletTabServiceImpl.java

적금 이자율 수정 6%를 0.06이 아닌 6으로 계산함

적금 이자율 수정 #162

---

src/main/webapp/WEB-INF/views/exchange/exchangeOfflineForm.jsp
src/main/webapp/WEB-INF/views/exchange/exchangeOnlineForm.jsp
src/main/webapp/WEB-INF/views/exchange/reExchangeOnlineForm.jsp

feat: 환전 페이지 alert 삭제

---

src/main/java/kb04/team02/web/mvc/group/controller/GroupWalletController.java
src/main/java/kb04/team02/web/mvc/group/entity/GroupWallet.java
src/main/java/kb04/team02/web/mvc/group/service/GroupWalletServiceImpl.java
src/main/webapp/WEB-INF/views/groupwallet/groupWalletDetail01.jsp
src/test/java/kb04/team02/web/mvc/service/groupwallet/GroupWalletServiceImplTest.java

feat: 모임지갑 삭제 #165

---

src/test/java/kb04/team02/web/mvc/ValidDataTest.java

개인지갑 외화 잔액 데이터 수정
- 개인지갑2에 데한 데이터가 개인지갑 1에대한 데이터로 삽입되어있는 것을 수정
개인지갑 내역 출력
- script 문법 오류 수정

개인지갑 외화 잔액 데이터 수정, 개인지갑 내역 출력

---

src/main/java/kb04/team02/web/mvc/exchange/controller/ExchangeController.java
src/main/java/kb04/team02/web/mvc/exchange/service/ExchangeService.java
src/main/java/kb04/team02/web/mvc/exchange/service/ExchangeServiceImpl.java

추가한 메소드들 충돌나는지 확인 #198

---

.gitignore
pom.xml
src/main/java/kb04/team02/web/mvc/KbFinalApplication.java
src/main/java/kb04/team02/web/mvc/exchange/controller/BankController.java
src/main/java/kb04/team02/web/mvc/exchange/dto/GeoCodeDto.java
src/main/java/kb04/team02/web/mvc/exchange/service/StaticMapService.java
src/main/webapp/WEB-INF/views/exchange/exchangeOfflineForm.jsp
src/test/java/kb04/team02/web/mvc/common/module/StaticMapServiceTest.java

Feat: 수령 지점 선택 시 네이버 지도 GET /bank/{id} #170

---

src/main/java/kb04/team02/web/mvc/group/service/GroupWalletServiceImpl.java
src/main/java/kb04/team02/web/mvc/group/service/GroupWalletTabServiceImpl.java
src/main/java/kb04/team02/web/mvc/saving/repository/InstallmentSavingRepository.java
src/main/java/kb04/team02/web/mvc/saving/repository/SavingHistoryRepository.java

적금 내역 추가 #225

---

src/main/java/kb04/team02/web/mvc/group/repository/GroupWalletRespository.java
src/main/java/kb04/team02/web/mvc/group/service/GroupWalletServiceImpl.java
src/main/java/kb04/team02/web/mvc/saving/entity/InstallmentSaving.java

fixed bug: 모임지갑 삭제 #231

---

pom.xml
src/main/java/kb04/team02/web/mvc/SwaggerConfig.java
src/main/java/kb04/team02/web/mvc/exchange/controller/ExchangeController.java
src/main/java/kb04/team02/web/mvc/exchange/dto/BankDto.java
src/main/java/kb04/team02/web/mvc/exchange/dto/ExchangeCalDto.java
src/main/java/kb04/team02/web/mvc/exchange/dto/ExchangeDto.java
src/main/resources/application.properties

exchangeController Swagger 적용 중 #235

---

src/main/java/kb04/team02/web/mvc/DataLoader.java

데이터 수정 #225
